name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Exercise 4
      id: exercise-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Exercise 4
        setup-command: pip install pytest
        command: pytest Exercises/Exercise_4/exercise_4_test.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCISE-4_RESULTS: "${{steps.exercise-4.outputs.result}}"
      with:
        runners: exercise-4
